# Paths
input_dir: inputs
output_dir: outputs
blast_database: ../databases/homd_all_genomes.fna
flanking_regions_filename: ../references/split_hcr_flanking_regions.csv

## Inputs
input_filenames: [
                  arcobacter_16s.fasta
                  ]
# If the targets are not present in the database leave
    # target_seqids_in_blast_db empty. If they are in the
    # database, provide a list of the target IDs as they 
    # are named in the database. This is for the filtering
    # step, so that we can remove the on target blast results
target_seqids_in_blast_db: []
target_naming: {'NZ_CP032823.1:785249-786766':'Acr_rrsA', 
                'NZ_CP032099.1:c1898141-1896624':'Ask_rrsA', 
                'NC_017187.1:c2171088-2169572':'Abu_rrsA'}
target_flanking: {'NZ_CP032823.1:785249-786766':'B2', 
                  'NZ_CP032099.1:c1898141-1896624':'B2', 
                  'NC_017187.1:c2171088-2169572':'B2'}
## Params
# Probes will have the same sequence as the input sequence, so they will hybridize 
    # to the reverse complement of the input sequence. If you want your probes to
    # hybridize to the input sequence set design_reverse_complement as True.
design_reverse_complement: True
probe_length:
    min_size: 18
    opt_size: 20
    max_size: 22
# If you want to design against a double stranded DNA database, set blast_strand 
    # to both. If you are only worried about things binding off target to RNA, 
    # set strand to minus
blast_strand: both
maximum_pair_distance_bp: 2
mch_filter: 12
tm_filter: 48
gc_filter: 7
minimum_bp_between_off_target_sites: 100
probe_selection:
    repetitions: 100
spacer: tat